Repository youki-dev/oci-spec-rs, pull requests merged in 2024-09, with the labels that each got.

#206 digest: Minor self-review fixups
  src/image/digest.rs
Labels: kind/cleanup

#207 Import reference
  Cargo.toml
  src/distribution/mod.rs
  src/distribution/reference.rs
Labels: kind/cleanup

#208 Enable `cargo audit`
  .github/workflows/security-audit.yml
Labels: kind/cleanup

#192 Update description of `cpu_affinity_final`
  src/runtime/process.rs
Labels: kind/runtime

#213 reference: use thiserror
  src/distribution/reference.rs
Labels: kind/cleanup

#212 Rework Digest
  src/image/descriptor.rs
  src/image/digest.rs
Labels: kind/cleanup

#215 Fix clippy false positive
  src/runtime/miscellaneous.rs
Labels: kind/test

#216 Update and pin GitHub actions
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/cross.yml
  .github/workflows/gh-pages.yml
  .github/workflows/label.yml
  .github/workflows/release.yml
Labels: kind/test

#214 Release 0.7.0
  Cargo.toml
  README.md
Labels: kind/cleanup

#219 Add get_mut to annotations and manifests in ImageIndex
  src/image/index.rs
Labels: kind/cleanup

#220 digest: Add more derives and trait impls
  src/image/digest.rs
Labels: kind/image

#222 digest: Add TryFrom<&str + String>
  src/image/digest.rs
Labels: kind/image

#223 manifest: Use `.parse()` over `from_str()` in a test
  src/image/manifest.rs
Labels: kind/test

#225 Replace actions-rs GitHub actions
  .github/workflows/ci.yml
Labels: kind/cleanup
